.TH "dell-satellite-sync" "8" "13 November 2013" "Version 1.0.2" ""

.SH NAME
dell-satellite-sync - Import Dell official yum repositories into RHN Satellite or Spacewalk server.

.SH SYNOPSIS
.nf
\fBdell-satellite-sync\fR [ --server-actions-only | --client-actions-only ] [ options ] 

.SH DESCRIPTION
.PP
\fBdell-satellite-sync\fR is a tool for taking the Dell OpenManage yum repositories, importing them into channels in an RHN Satellite or Spacewalk server, and subscribing registered Dell systems to the correct channels. It uses native APIs, so it can be run by non-root users as long as valid RHN login credentials are provided.

.SS "COMMON OPTIONS"
 \fB-h, --help\fR 
 Print help message and exit.

 \fB-u \fIUSER\fB --user=\fIUSER\fB\fR
 Satellite username.

 \fB-p \fIPASSWORD\fB, --password=\fIPASSWORD\fB\fR
 Satellite password.

 \fB-s \fISATSERVER\fB, --satserver=\fISATSERVER\fB\fR
 FQDN of Satellite server.

 \fB-v, --verbose\fR
 Enable verbose output.

 \fB-D, --debug\fR
 Print lots of extra and ugly (but potentially useful) output.

.SS "SERVER-ACTION OPTIONS"
 \fB-S, --server-actions-only\fR
 Create channels and upload RPMs, skip system subscriptions.

 \fB-r \fIREPOSITORY\fB, --repo=\fIREPOSITORY\fB\fR
 Location of Dell yum repositories. Defaults to \fIhttp://linux.dell.com/repo/hardware/latest\fB.

 \fB-c \fICHANNEL\fB, --channel=\fICHANNEL\fB\fR
 OS parent channel to use. e.g. \fIrhel4\fB, \fIrhel5\fB, \fIrhel6\fB or \fIsles11\fB.

 \fB-o \fILIST_OF_SYSTEMS\fB, --only-systems=\fILIST_OF_SYSTEMS\fB\fR
 Only create child channels for these systems. e.g. -o per720,per620,pet620

 \fB-a, --all-systems\fR
 Create system-specific channels for ALL supported Dell systems.

 \fB-d, --delete\fR
 Delete all unused Dell channels and packages for a given OS channel.

.SS "CLIENT-ACTION OPTIONS"
 \fB-C, --client-actions-only\fR
 Subscribe systems to corresponding child channels.

.fi
.SH OVERVIEW
.PP
For an overview, see \fB/usr/share/doc/dell-satellite-sync-<version>/README\fR

.SH "EXAMPLES"
For usage examples, see \fB/usr/share/doc/dell-satellite-sync-<version>/EXAMPLES\fR

.SH FILES
.ta
.nf
/usr/bin/dell-satellite-sync
/usr/share/dell-satellite-sync/dell-satellite-sync.py
/etc/sysconfig/dell-satellite-sync/dell-satellite-sync.conf
/etc/sysconfig/dell-satellite-sync/dell-system-ids
.fi

.SH AUTHOR
.ta
.nf
Vinny Valdez <vvaldez@redhat.com>
Jose De la Rosa <jose_de_la_rosa@dell.com>
.fi

.SH REPORTING BUGS
Report bugs to <linux-poweredge@dell.com>

.SH SEE ALSO
For additional information and code contributions, visit \fBhttp://linux.dell.com/dell-satellite-sync\fR.
