.TH "DELL-SATELLITE-SYNC" "8" "9 November 2009" "Version 0.4.2" ""

.SH NAME
dell-satellite-sync \- synchronizes Dell linux repositories into an RHN Satellite or Spacewalk server, and subscribes Dell systems to the correct channels.

.SH SYNOPSIS

.nf

\fBdell-satellite-sync\fR [ \fBoptions \fI\&...\fB\fR ] 

 [ \fB-4\fR ] [ \fB--rhel4-only\fR ]

 [ \fB-5\fR ] [ \fB--rhel5-only\fR ]

 [ \fB-a\fR ] [ \fB--all\fR ]

 [ \fB-c\fR ] [ \fB--client-mode\fR ]

 [ \fB-C\fR ] [ \fB--client-actions-only\fR ]

 [ \fB-d\fR ] [ \fB--delete\fR ]

 [ \fB-D\fR ] [ \fB--demo\fR ]

 [ \fB--debug\fR ]

 [ \fB-f\fR ] [ \fB--force\fR ]

 [ \fB-g\fIURL\fB\fR ] [ \fB--gpg-url=\fIURL\fB\fR ]

 [ \fB-l\fIDIRECTORY\fB\fR ] [ \fB--localdir=\fIDIRECTORY\fB\fR ]

 [ \fB--no-packages\fR ]

 [ \fB--no-rsync\fR ]

 [ \fB-o\fILIST_OF_SYSTEMS\fB\fR ] [ \fB--only-systems=\fILIST_OF_SYSTEMS\fB\fR ]

 [ \fB-p\fIPASSWORD\fB\fR ] [ \fB--password=\fIPASSWORD\fB\fR ]

 [ \fB-r\fIREPOSITORY\fB\fR ] [ \fB--repo=\fIREPOSITORY\fB\fR ]

 [ \fB-s\fIHOSTNAME\fB\fR ] [ \fB--server=\fIHOSTNAME\fB\fR ]

 [ \fB-S\fR ] [ \fB--server-actions-only\fR ]

 [ \fB-u\fIUSER\fB\fR ] [ \fB--user=\fIUSER\fB\fR ]

 [ \fB-v\fR ] [ \fB--verbose\fR ]


.fi
.SH DESCRIPTION
.PP
The Dell Satellite Sync tool (\fBdell-satellite-sync\fR) will synchronize the Dell official Linux software repositories into an RHN Satellite or Spacewalk server, and subscribe any registered systems that have a Dell vendor id to the correct child channel.

By default, two sets of actions are performed: \fBserver-side actions\fR and \fBclient-side actions\fR

.SS "SERVER-SIDE ACTIONS"
.PP
The following steps are performed during this phase:

1. \fIrsync\fR is used to obtain a copy of the Dell official Linux repositories.  The default URL for this is \fBlinux.dell.com/repo/hardware/latest/\fR - this can be changed with the \fB--repo\fR option as needed.  If a local copy of the repositories already exists, this can be skipped with \fB--no-rsync\fR.

2. Child channels are created representing each Dell hardware system for any base channels found on the server.  The current Dell repositories contain 49 hardware systems.  Supported base channels are Red Hat Enterprise Linux version 4 and 5, both i386 and x86_64, and any derivative of these (e.g. z-stream, long life).  To reduce the number of child channels created, specify the types of systems you would like managed with the \fB--only-systems\fR option.

3. An additional child channel is also created for each base channel that contains platform independent Dell software.

4. Each child channel is populated with rpms from the corresponding local repository using \fIrhnpush\fR, which must be installed.  This dependency is not built into the rpm because the client-side actions do not require it, which can be run separately.

.SS "CLIENT-SIDE ACTIONS"
The following steps are performed during this phase:

1. A list of all registered systems is compiled and any without a Dell vendor id are skipped.  The remaining systems continue through these steps.  This behavior can be overriden with the \fB--all\fR option.

2. Two GPG keys from Dell are installed via a remote action on each system. See the section \fBPRE-REQUISITES\fR for details on allowing remote actions.  By default the keys are obtained from the specified repository (default \fBhttp://linux.dell.com/repo/hardware/latest/\fR), but can be explicitly specified with \fB--gpg-url\fR.

3. The systems are subscribed to the Dell platform independent child channel.

4. The package \fIsmbios-utils\fR and dependencies are scheduled for remote install on each system.

5. A remote action is run on each system to execute \fIsmbios-sys-info\fR.  This reports the BIOS hardware id of the system.  This information is used to subscribe the system to the correct child channel.

.SS "PRE-REQUISITES
For the server-side actions to complete, the \fIrhnpush\fR package must be installed on the system running \fBdell-satellite-sync\fR.

For the client-side actions to complete, The following conditions must be met:

o All registered systems must belong to their respective \fIrhn-tools\fR child channel.

o The systmes must have the \fIprovisioning\fR entitlement.

o The package \fIrhncfg-actions\fR must be installed.

o Remote actions must be allowed by running the command "\fIrhn-actions-control --enable-run\fR" (this can be accomplished through an rpm and pushed to the clients, or by another means outside of RHN Satellite/Spacewalk).

o The \fIosad\fR package should be installed and started on the clients.  This allows very quick execution of remote actions and package installs, rather than waiting for the default 2 hour check-in interval.

.SH "OPTIONS"
.SS "COMMON OPTIONS"
.TP
\fB-D, --demo\fR
Run in simulation mode.  Does not connect to any servers or clients.
.TP
\fB-g\fIURL\fB, --gpg-url=\fIURL\fB\fR
URL where GPG keys are available to he systems. If this option is not specified, first a default of \fBhttp://linux.dell.com/repo/hardware/latest/\fR is used, otherwise if \fB--repo\fR is specified, then that location will be used.
.TP
\fB-h, --help\fR
Display list of options
.TP
\fB-o\fILIST_OF_SYSTEMS\fB, --only-systems=\fILIST_OF_SYSTEMS\fB\fR
Only rsync and create child channels for systems in LIST_OF_SYSTEMS e.g. \fB--only-systems pe1800,per900\fR
.TP
\fB-p\fIPASSWORD\fB, --password=\fIPASSWORD\fB\fR
Password for the user specified with \fB--user\fR.  If this option is not specified, it will be prompted for.
.TP
\fB-r\fIREPOSITORY\fB, --repo=\fIREPOSITORY\fB\fR
Repository to call \fIrsync\fR against.  Also used to construct location of GPG keys, if \fB--gpg-url\fR is not specified.
.TP
\fB-s\fIHOSTNAME\fB, --server=\fIHOSTNAME\fB\fR
Hostname of your RHN Satellite/Spacewalk server (required).
.TP
\fB-u\fIUSERNAME\fB, --user=\fIUSERNAME\fB\fR
Username for RHN Satellite/Spacewalk (required).
.TP
\fB-v, --verbose\fR
Print extra information.

.SS "SERVER-SIDE ACTIONS"
.TP
\fB-4, --rhel4-only\fR
Only work under Red Hat Enterprise Linux 4 base channels (as of version 0.4, either this or 
.B --rhel5-only 
are required)
.TP
\fB-5, --rhel5-only\fR
Only work under Red Hat Enterprise Linux 5 base channels (as of version 0.4, either this or 
.B --rhel4-only 
are required)
.TP
\fB-d, --delete\fR
Delete all Dell child channels and packages.  Packages can be left on the server with \fB--no-packages\fR.
.TP
\fB-f, --force\fR
Force package upload via \fIrhnpush\fR (required for version 0.4)
.TP
\fB-l\fIDIRECTORY\fB, --localdir=\fIDIRECTORY\fB\fR
Local directory to hold a copy of the Dell repositories.  This option is also needed when specifying \fB--delete\fR, since the channel list is built from this directory tree (required).
.TP
\fB--no-packages\fR
Do not push or delete any packages.
.TP
\fB--no-rsync\fR
Do not call \fIrsync\fR to syncronize the Dell repositories.  A local copy must already exist at \fB--localdir\fR.
.TP
\fB-S, --server-actions-only\fR
Only perform server-side actions, including calling \fIrsync\fR, creating child channels, and uploading rpms via \fIrhnpush\fR.

.SS "CLIENT-SIDE ACTIONS"
.TP
\fB-a, --all\fR
Perform client actions on all systems, regardless of vendor id.  This will subscribe all clients to the Dell platform independent software channel, and attempt to determine the BIOS hardware id.  Note that a matching child channel may not exist if it is not a Dell system.
.TP
\fB-C, --client-actions-only\fR
Only perform client-side actions, including scheduling remote actions, installing package, and subscribing systems.  Channels and rpms must already be on the server.

.SS "DEBUGGING AND EXPERIMENTAL OPTIONS"
.TP
\fB--auto\fR
Automatically determine what types of Dell systems are registered with RHN Satellite/Spacewalk, and rsync/create child channels for only those types, essentially internally invoking \fB--only-systems\fR (not implemented yet).
.TP
\fB-C, --client-mode\fR
Runs client actions from a client.  Use this to avoid using remote actions, and supply the authentication client-side instead. (not implemented yet).
.TP
\fB--debug\fR
Print lots of extra and ugly (but potentially useful) output.

.RE

.SH "EXAMPLES"

\fBsatellite-sync --list-channels\fR

\fBsatellite-sync --channel=rhel-i386-as-3\fR

\fBsatellite-sync -c rhel-i386-as-3 -c redhat-advanced-server-i386\fR

\fBsatellite-sync -m /var/tmp/channel-dumps --list-channels\fR

\fBsatellite-sync -m /var/tmp/channel-dumps -c rhel-i386-as-3\fR

\fBsatellite-sync --iss-parent=stage-satellite.yourorg.com -c rhel-i386-as-4\fR
.SH "SEE ALSO"

db-control(1) - embedded database environment only!

rhn-charsets(8)

rhnpush(8)

rhn-satellite-activate(8)

rhn-schema-version(8)

rhn-ssl-dbstore(8)
.SH "AUTHORS"

Todd Warner <taw@redhat.com>

Mihai Ibanescu <misa@redhat.com>

Pradeep Kilambi <pkilambi@redhat.com>

.SH SEE ALSO
	rsync(1)

.SH FILES
	/usr/bin/dell-satellite-sync

.SH AUTHORS
	Vinny Valdez <vvaldez@redhat.com>
